/* Maquette isolée : données fictives et interactions en mémoire uniquement. */
'use strict';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escapeHtml = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iconPaths = {
  plus:'M12 5v14M5 12h14', minimize:'M8 3v5H3m18 0h-5V3M3 16h5v5m8 0v-5h5',
  maximize:'M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5', close:'M6 6l12 12M18 6L6 18',
  sparkle:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',
  people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3a4 4 0 0 1 0 8m6 10v-2a4 4 0 0 0-3-3.87M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Zm0 0v6h6M8 13h8M8 17h5',
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[name] || iconPaths.file}"/></svg>`;
$$('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});

// Camille reprend le contexte fictif du scénario de démonstration. Les autres profils illustrent les états de l’interface.
const learners = [
  {id:'camille',name:'Camille Martin',initials:'CM',color:'',job:'Responsable opérations',company:'Services aux entreprises',short:'Transformer les échanges clients en comptes rendus et plans d’action.',status:'Informations à préciser',warn:true,prep:12,totalPrep:13,attendance:[true,true,false,false],quiz:false,satisfaction:false,proofUrl:null,updated:'21 septembre 2026',
    sections:[['Contexte professionnel','Coordonne les opérations et le suivi client dans une entreprise de services. Prépare régulièrement des comptes rendus et des relances. Les outils réellement utilisés restent à préciser.'],['Objectif concret','Préparer plus vite ses comptes rendus et structurer ses relances clients. Elle souhaite repartir avec une méthode directement applicable à son quotidien.'],['Pratique actuelle et aisance','Les usages réguliers de l’IA ne sont pas renseignés. Les réponses déclarées suggèrent de vérifier les gestes de base au tour de table, sans déduire son autonomie du niveau de session choisi.'],['Points d’attention','Faire préciser le format de ses notes d’entrée et le livrable attendu avant de proposer un assistant. Distinguer rédaction d’un message et envoi automatique.'],['À clarifier avec elle','Quels outils utilise-t-elle réellement chaque semaine ? Quel compte rendu lui prend le plus de temps ? Comment reconnaîtrait-elle un résultat utile ?']],source:'Exemple pédagogique du scénario de démonstration · Positionnement fictif actualisé le 21 septembre'},
  {id:'thomas',name:'Thomas Durand',initials:'TD',color:'teal',job:'Consultant indépendant',company:'Conseil',short:'Structurer ses propositions commerciales et réutiliser ses méthodes.',status:'Profil renseigné',warn:false,prep:13,totalPrep:13,attendance:[true,true,false,false],quiz:true,satisfaction:false,proofUrl:null,
    sections:[['Contexte professionnel','Consultant indépendant. Il analyse les besoins de ses clients et rédige des propositions commerciales. Il travaille avec Word, PowerPoint et des notes de rendez-vous.'],['Objectif concret','Passer d’un échange client à une proposition structurée, en gardant la maîtrise des engagements et du contenu.'],['Pratique actuelle et aisance','Utilise déjà un assistant conversationnel pour reformuler. Il souhaite apprendre à donner du contexte et à obtenir des résultats plus réguliers.'],['Points d’attention','Partir d’une proposition anonymisée et vérifier les éléments factuels. Proposer une variante plus autonome lorsqu’il termine un exercice.'],['À clarifier avec lui','Quelle partie d’une proposition réécrit-il le plus souvent ?']],source:'Données fictives de maquette · Exemple de notes closing et de questionnaire'},
  {id:'sarah',name:'Sarah Petit',initials:'SP',color:'coral',job:'Chargée de communication',company:'Association',short:'Décliner une idée en publications et en supports de communication.',status:'Profil renseigné',warn:false,prep:8,totalPrep:13,attendance:[true,false,false,false],quiz:false,satisfaction:false,proofUrl:null,
    sections:[['Contexte professionnel','Prépare les publications et les supports d’une association. Elle utilise Canva et un calendrier éditorial partagé.'],['Objectif concret','Construire une série de contenus cohérente à partir d’une idée, sans perdre le ton propre à son organisation.'],['Pratique actuelle et aisance','A déjà expérimenté la rédaction avec l’IA. Elle cherche surtout à mieux organiser ses demandes et à décliner des variantes.'],['Points d’attention','Prévoir un exemple créatif dans une session majoritairement orientée documents. Garder une phase de choix et de réécriture humaine.'],['À clarifier avec elle','Quel public veut-elle toucher et quels éléments de ton doivent rester constants ?']],source:'Données fictives de maquette · Exemple de questionnaire et de contexte professionnel'},
  {id:'alex',name:'Alex Bernard',initials:'AB',color:'slate',job:'Métier non renseigné',company:'À préciser',short:'Ses objectifs et ses usages de l’IA restent à recueillir.',status:'Profil incomplet',warn:true,prep:0,totalPrep:13,attendance:[false,false,false,false],quiz:false,satisfaction:false,proofUrl:null,
    sections:[['Contexte professionnel','Non renseigné.'],['Objectif concret','Non renseigné.'],['Pratique actuelle et aisance','Aucune information disponible. Aucun niveau ni besoin ne peut être déduit de son inscription.'],['Points d’attention','Le profil incomplet n’empêche pas de préparer le reste de la session. Prévoir un échange à l’accueil pour préciser son besoin.'],['À clarifier avec lui','Quel est son métier ? Quelle tâche souhaite-t-il améliorer ? A-t-il déjà utilisé un outil d’IA ?']],source:'Données fictives de maquette · Questionnaire non reçu'},
];
const copiedPages = [
  {id:'j1',label:'Support J1',title:'Jour 1 · Explorer et pratiquer',intro:'Comprendre les usages de l’IA, expérimenter et construire une première méthode.',parts:[['Bienvenue et tour de table','Présentez votre métier et un résultat concret que vous souhaitez obtenir pendant ces deux jours.'],['Formuler une demande utile','Travaillez le contexte, le résultat attendu et les critères de qualité à partir d’un cas professionnel.'],['Atelier · Du document à l’action','Transformez un ensemble de notes en compte rendu, puis en plan d’action.'],['Atelier · Créer avec Lovable','Présentez le besoin, construisez une première version et échangez sur les résultats.']]},
  {id:'j2',label:'Support J2',title:'Jour 2 · Adapter à son métier',intro:'Approfondir les usages et construire des assistants utiles au quotidien.',parts:[['Reprise et questions ouvertes','Revenez sur les expériences du jour 1 et les questions à approfondir.'],['Construire son assistant métier','Définissez sa mission, les informations dont il a besoin et le format du résultat attendu.'],['Cas d’usage personnalisés','Déclinez le même atelier pour les documents clients, les propositions commerciales ou les contenus de communication.'],['Bilan et suites de la formation','Retrouvez le quiz, la satisfaction et vos prochaines étapes dans votre espace apprenant.']]},
  {id:'additionnels',label:'Contenus additionnels',title:'Contenus additionnels',intro:'La copie de cette page appartient à la session des 13 et 14 octobre.',parts:[['Préparer un effet wow','Partir d’un exemple concret de l’apprenant, montrer une première transformation puis expliquer comment reproduire le résultat.'],['Documents et suivi client','Exemples de comptes rendus, de plans d’action et de relances à adapter pendant les ateliers.'],['Création de contenu','Variantes pour décliner une idée selon le public, le canal et le ton de l’organisation.'],['Prompts pour aller plus loin','Consultez les pistes de la synthèse de session et adaptez-les avec le formateur.']]},
  {id:'amont',label:'Avant la formation',title:'Avant la formation',intro:'Retrouvez les repères et les liens pour arriver dans de bonnes conditions.',parts:[['Préparer mon ordinateur','Les tâches à cocher sont dans l’étape « Préparer ma formation » de votre espace apprenant.'],['Comment utiliser ces supports','Ouvrez les sections au fur et à mesure des ateliers. Les contenus additionnels restent disponibles depuis la même navigation.']]},
  {id:'certification',label:'Préparation certification',title:'Préparer la certification',intro:'Page pédagogique de démonstration pour les participants concernés.',parts:[['Comprendre la suite du parcours','Les modalités et les ressources exactes sont celles de la page dupliquée pour la session.'],['Retrouver mes prochaines étapes','Consultez votre espace apprenant pour connaître les actions qui vous concernent.']]},
];
let activePage='dashboard';
let questions=[];
let slidesLink='';
const completed=new Set(['prep-0','prep-1']);
const tasks=[
 {id:'prep',name:'Préparer & démarrer',sub:'À partir de J−14',open:true,items:[
  ['Créer le groupe WhatsApp et ajouter les apprenants, les référents de la formation','external','Ouvrir l’action'],
  ['Envoyer un message de présentation sur le groupe WhatsApp','external','Voir le message'],
  ['Dupliquer & modifier le Canva','canva','Renseigner les slides'],
  ['Lire la synthèse du groupe et les profils des apprenants','profiles','Ouvrir le dashboard'],
  ['Vérifier les préparatifs des apprenants','progress','Voir la progression'],
  ["Préparer un cas d’usage effet wow par participant",'wow','Synthèse et ressource'],
  ['Station F uniquement : inviter les apprenants sur HAL pour les deux jours','external','Ouvrir l’action'],
  ['Envoyer le message WhatsApp la veille du J1','external','Voir le message'],
 ]},
 {id:'formation',name:'En formation',sub:'Jour 1 · Jour 2',open:false,groups:[
  ['Matin J1',[
   ['Réserver le restaurant pour le nombre de personnes confirmé','external','Ouvrir l’action'],['Acheter les viennoiseries et les bouteilles d’eau'],['Accueillir et échanger avec tous les participants'],['Faire émarger tout le monde et vérifier','progress','Voir les émargements'],['Expliquer le fonctionnement des supports aux apprenants','j1','Ouvrir le support J1'],['Expliquer la certification et annoncer l’inscription ensemble en fin de J2'],
  ]],
  ['Après-midi J1',[["Annoncer le partage LinkedIn du gagnant de l’atelier Lovable"],['Prendre une photo avec le gagnant et les participants','external','Déposer la photo']]],
  ['Soir J1',[
   ['Partager la photo Lovable à France IA et demander le post LinkedIn','external','Ouvrir l’action'],['Générer les instructions des assistants personnalisés','wow','Voir les pistes'],['Ajouter des contenus pertinents au profil du groupe','additionnels','Contenus additionnels'],['Ajouter l’ensemble des diapositives à la session','canva','Renseigner les slides'],['Prévenir le groupe WhatsApp en cas de changement de salle'],['Qualifier les participants (J1)','qualification','Qualifier'],['Signaler une forte hétérogénéité dans le groupe','external','Ouvrir l’action'],
  ]],
  ['Matin J2',[
   ['Réserver le restaurant pour le nombre de personnes confirmé','external','Ouvrir l’action'],['Faire émarger tout le monde et vérifier','progress','Voir les émargements'],['Présenter les contenus additionnels et expliquer la personnalisation du jour 2','additionnels','Contenus additionnels'],
  ]],
  ['Après-midi J2',[
   ['Faire émarger tout le monde et vérifier','progress','Voir les émargements'],['Faire la démo effet wow','wow','Voir les pistes'],['Vérifier que tout le monde a complété le quiz','progress','Voir le quiz'],['Inscrire ensemble les apprenants CPF à la certification','external','Ouvrir le suivi'],['Prendre la photo de groupe et la déposer','external','Déposer la photo'],['Vérifier tous les émargements et relancer si nécessaire','progress','Contrôle final'],['Renseigner les cas d’usage et le compte rendu de session','feedback','Feedback de session'],['Envoyer le message de fin WhatsApp ; ajouter Trustpilot si les apprenants sont très satisfaits','external','Voir le message'],['Proposer un follow-up aux dirigeants et indépendants','external','Ouvrir l’action'],['Qualifier les participants et saisir mon feedback final','qualification','Qualifier et compléter'],
  ]],
 ]},
];
function taskRow(item,id){return `<div class="task-row"><input type="checkbox" aria-label="${escapeHtml(item[0])}" data-task="${id}" ${completed.has(id)?'checked':''}><div><div class="task-label">${escapeHtml(item[0])}</div>${item[1]?`<button class="task-action" data-action="${item[1]}">${escapeHtml(item[2])} <span aria-hidden="true">↗</span></button>`:''}</div></div>`;}
function taskMarkup(){return tasks.map((phase,i)=>{const items=phase.items||phase.groups.flatMap(g=>g[1]);const done=items.filter((_,j)=>completed.has(`${phase.id}-${j}`)).length;let n=0;const content=phase.items?phase.items.map((t,j)=>taskRow(t,`${phase.id}-${j}`)).join(''):phase.groups.map(g=>`<div class="task-group-label">${escapeHtml(g[0])}</div>${g[1].map(t=>taskRow(t,`${phase.id}-${n++}`)).join('')}`).join('');return `<details class="phase" data-phase="${phase.id}" ${phase.open?'open':''}><summary><span class="phase-number">${i+1}</span><span class="phase-name">${phase.name}<small>${phase.sub}</small></span><span class="phase-total" data-total="${phase.id}">${done}/${items.length}</span><span class="phase-arrow">›</span></summary>${content}</details>`;}).join('');}
$('#task-list').innerHTML=taskMarkup();
$('#task-list').addEventListener('change',e=>{const id=e.target.dataset.task;if(!id)return;e.target.checked?completed.add(id):completed.delete(id);const phase=tasks.find(p=>id.startsWith(p.id+'-'));const items=phase.items||phase.groups.flatMap(g=>g[1]);$(`[data-total="${phase.id}"]`).textContent=`${items.filter((_,j)=>completed.has(`${phase.id}-${j}`)).length}/${items.length}`;});
$('#task-list').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)runAction(b.dataset.action);});

function renderTabs(){const pages=[{id:'dashboard',label:'Dashboard'},...copiedPages];$('#page-tabs').innerHTML=pages.map(p=>`<button role="tab" id="tab-${p.id}" aria-selected="${p.id===activePage}" aria-controls="page-content" data-page="${p.id}">${p.label}</button>`).join('');$('#page-content').setAttribute('role','tabpanel');$('#page-content').setAttribute('aria-labelledby',`tab-${activePage}`);}
function renderPage(){renderTabs();$('#page-content').innerHTML=activePage==='dashboard'?dashboardMarkup():supportMarkup(copiedPages.find(p=>p.id===activePage));$('#page-content').scrollTop=0;}
function setPage(id){activePage=id;renderPage();$('#task-rail').classList.remove('mobile-open');$('#task-toggle').setAttribute('aria-expanded','false');}
$('#page-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)setPage(b.dataset.page);});
$('#page-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const pages=['dashboard',...copiedPages.map(p=>p.id)];let n=pages.indexOf(activePage);n=e.key==='Home'?0:e.key==='End'?pages.length-1:(n+(e.key==='ArrowRight'?1:-1)+pages.length)%pages.length;setPage(pages[n]);$(`#tab-${activePage}`).focus();});

function dashboardMarkup(){return `<section aria-labelledby="group-heading"><div class="section-heading"><h2 id="group-heading">${icon('sparkle')}Synthèse du groupe</h2><span class="muted">Exemple de synthèse pédagogique</span></div><div class="surface">
 <p class="summary-intro">Un groupe tourné vers des résultats concrets : transformer des échanges en documents utiles, structurer ses propositions et créer du contenu. <strong>Le fil rouge : passer d’une matière brute à un livrable prêt à retravailler.</strong></p>
 <div class="summary-grid"><div><h3>Ce qui réunit le groupe</h3><p>Camille et Thomas cherchent à mieux exploiter leurs échanges clients. Sarah apporte un besoin de création de contenu. Un même atelier peut donner lieu à plusieurs livrables métier.</p></div><div class="attention"><h3>À garder en tête</h3><p>Le profil d’Alex reste à compléter. Vérifier les usages réels au tour de table et prévoir une variante guidée. Le métier ne permet pas, à lui seul, de déduire l’aisance.</p></div></div>
 <details class="summary-extra" id="workshop-ideas"><summary>Pistes d’atelier, effets wow et prompts</summary><div class="case-grid"><article class="case"><span class="pill">Documents · Camille et Thomas</span><h3>Des notes au plan d’action</h3><p>Transformer des notes fictives en compte rendu, actions et relance. Faire préciser le destinataire et les éléments à vérifier.</p><button class="btn-link" data-prompt="documents">Voir le prompt →</button></article><article class="case"><span class="pill">Communication · Sarah</span><h3>Une idée, plusieurs formats</h3><p>Décliner une idée en publication, email et support. Comparer le ton et les choix selon le public.</p><button class="btn-link" data-prompt="contenu">Voir le prompt →</button></article></div><div class="profile-section" style="margin-top:18px"><h3>Questions d’ouverture</h3><p>Quel livrable vous prend le plus de temps ? Quels outils utilisez-vous vraiment ? À quoi reconnaîtrez-vous que ces deux jours vous ont été utiles ?</p></div><button class="btn-link" data-go="additionnels">Consulter la ressource « Préparer un effet wow » →</button></details>
 <div class="source-line">${icon('file')}3 profils renseignés ou partiels · 1 profil à compléter · Aucun score d’orientation</div></div></section>
 <section class="learners-section" aria-labelledby="learners-heading"><div class="section-heading"><h2 id="learners-heading">${icon('people')}Les apprenants <span class="pill neutral">4</span></h2><span class="muted">Cliquer pour consulter une fiche</span></div><div class="learner-grid">${learners.map(l=>`<button class="learner-card" data-learner="${l.id}" aria-label="Ouvrir le profil de ${l.name}"><div class="learner-card-head"><span class="avatar ${l.color}">${l.initials}</span><div><div class="learner-card-name">${l.name}</div><div class="learner-card-job">${l.job}</div></div></div><p class="card-expectation">${l.short}</p><div class="learner-card-bottom"><span class="pill ${l.warn?'warn':'neutral'}">${l.status}</span><span class="open-label">Voir le profil ↗</span></div></button>`).join('')}</div></section>`;}
function supportMarkup(p){const readOnly=$$('dialog[data-kind="learner-space"][open]').length>0;return `<article class="support-paper"><div class="support-cover"></div><div class="support-body"><span class="support-tag">PAGE DE LA SESSION · CONTENU DE DÉMONSTRATION</span><h1>${p.title}</h1><p>${p.intro}</p>${p.id==='j1'||p.id==='j2'?`<div class="support-callout"><strong>Diapositives de la session</strong><br>${slidesLink?`Lien renseigné : ${escapeHtml(slidesLink)}`:'Le lien vers les diapositives sera renseigné depuis la tâche Canva.'}${readOnly?'':'<br><button class="btn-link" data-canva>Ouvrir l’action Canva →</button>'}</div>`:''}${p.parts.map((part,i)=>`<details class="support-section" ${i===0?'open':''}><summary>${part[0]}</summary><p>${part[1]}</p></details>`).join('')}</div></article>`;}
$('#page-content').addEventListener('click',e=>{const learner=e.target.closest('[data-learner]');if(learner)openProfile(learner.dataset.learner);const prompt=e.target.closest('[data-prompt]');if(prompt)openPrompt(prompt.dataset.prompt);const go=e.target.closest('[data-go]');if(go)setPage(go.dataset.go);if(e.target.closest('[data-canva]'))openCanva();});

function modal({title,sub='',body,footer='',wide=false,narrow=false,kind='generic'}){const d=document.createElement('dialog');d.className=wide?'wide':narrow?'narrow':'';d.dataset.kind=kind;const h='dialog-title-'+Math.random().toString(36).slice(2);d.setAttribute('aria-labelledby',h);d.innerHTML=`<div class="dialog-head"><div class="dialog-heading-row"><h2 id="${h}">${escapeHtml(title)}</h2><button type="button" class="close-btn" data-close aria-label="Fermer">${icon('close')}</button></div>${sub?`<p>${escapeHtml(sub)}</p>`:''}</div><div class="dialog-body">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;document.body.append(d);d.addEventListener('click',e=>{if(e.target.closest('[data-close]'))d.close();if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{d.remove();});d.showModal();return d;}
function openProfile(id){const l=learners.find(x=>x.id===id);const d=modal({title:l.name,sub:l.job,kind:'profile',body:`<div class="profile-identity"><span class="avatar ${l.color}">${l.initials}</span><div class="profile-meta"><strong>${l.company}</strong><p>Session Niveau 1 · Rythme intermédiaire choisi</p></div><button class="btn btn-s" data-space>Espace apprenant ↗</button></div><div class="profile-tabs" role="tablist" aria-label="Informations de l’apprenant"><button role="tab" aria-selected="true" data-profile-tab="ai">Résumé IA</button><button role="tab" aria-selected="false" data-profile-tab="proof">Capture ARD</button></div><div class="profile-detail"></div>`,footer:'<button class="btn btn-s" data-close>Revenir à la session</button>'});
 const draw=tab=>{$$('.profile-tabs button',d).forEach(b=>b.setAttribute('aria-selected',String(b.dataset.profileTab===tab)));$('.profile-detail',d).innerHTML=tab==='ai'?`${l.id==='alex'?'<div class="profile-callout" style="margin-bottom:20px">Le questionnaire n’est pas disponible. Les informations manquantes restent à recueillir.</div>':''}${l.sections.map(s=>`<section class="profile-section"><h3>${s[0]}</h3><p>${s[1]}</p></section>`).join('')}<div class="profile-source">${l.source}</div>`:l.proofUrl?`<img class="proof-image" src="${escapeHtml(l.proofUrl)}" alt="Capture ARD originale conservée comme preuve"><p class="profile-source">Preuve initiale · Les réponses actualisées peuvent être différentes.</p>`:`<div class="empty-proof">${icon('file')}<h3>Capture ARD originale</h3><p>Aucune capture réelle n’est fournie pour cet apprenant fictif. Dans DELIV’IA, cette vue ouvrira le fichier déjà conservé comme preuve.</p><p>Le questionnaire ne sera pas reconstruit dans cette fiche.</p></div>${l.updated?`<p class="profile-source">Dans cet exemple, le positionnement a été actualisé le ${l.updated}. La preuve initiale reste inchangée ; le résumé utilise les réponses les plus récentes.</p>`:''}`;};draw('ai');d.addEventListener('click',e=>{const b=e.target.closest('[data-profile-tab]');if(b)draw(b.dataset.profileTab);if(e.target.closest('[data-space]'))openLearnerSpace(l);});}
function openLearnerSpace(l){const d=modal({title:'Espace apprenant',sub:l.name+' · Aperçu de démonstration',kind:'learner-space',body:`<div class="eyebrow">PARCOURS DE FORMATION</div><h2>Préparer ma formation</h2><p class="muted" style="margin:12px 0">${l.prep}/${l.totalPrep} préparatifs cochés. Comptez 30 minutes à 1 h 30.</p><div class="mini-progress" style="width:100%;height:6px"><span style="width:${l.prep/l.totalPrep*100}%"></span></div><div class="status-line" style="margin-top:22px">Cet aperçu montre uniquement la progression de l’étape de préparation. Les actions personnelles de l’apprenant restent dans son espace.</div><h3 style="margin:22px 0 12px">Consulter mes supports de formation</h3><div style="display:flex;flex-wrap:wrap;gap:8px">${copiedPages.map(p=>`<button class="btn btn-s" data-support="${p.id}">${p.label}</button>`).join('')}</div>`,footer:'<button class="btn btn-s" data-close>Revenir au profil</button>'});d.addEventListener('click',e=>{const b=e.target.closest('[data-support]');if(b)modal({title:copiedPages.find(p=>p.id===b.dataset.support).label,body:supportMarkup(copiedPages.find(p=>p.id===b.dataset.support)),kind:'support-preview',footer:'<button class="btn btn-s" data-close>Revenir à l’espace apprenant</button>'});});}
function openProgress(){const d=modal({title:'Progression des apprenants',sub:'Session fictive · 13 & 14 octobre 2026',kind:'progress',wide:true,body:`<div class="status-line"><strong>Préparation</strong> : seules les tâches de l’étape « Préparer ma formation » sont comptées.</div><div class="table-wrap"><table class="progress-table"><thead><tr><th>Apprenant</th><th>Préparation</th><th>Émargements<br><span style="font-size:9px">J1 matin · J1 après-midi · J2 matin · J2 après-midi</span></th><th>Quiz</th><th>Satisfaction</th></tr></thead><tbody>${learners.map(l=>`<tr><td><button data-progress-learner="${l.id}">${l.name}</button></td><td>${l.prep}/${l.totalPrep}<div class="mini-progress"><span style="width:${l.prep/l.totalPrep*100}%"></span></div></td><td><div class="attendance">${l.attendance.map((ok,i)=>`<span class="${ok?'signed':''}" title="${['J1 matin','J1 après-midi','J2 matin','J2 après-midi'][i]} : ${ok?'signé':'à faire'}" aria-label="${['J1 matin','J1 après-midi','J2 matin','J2 après-midi'][i]} : ${ok?'signé':'à faire'}">${ok?'✓':'—'}</span>`).join('')}</div></td><td><span class="pill ${l.quiz?'ok':'neutral'}">${l.quiz?'Complété':'À faire'}</span></td><td><span class="pill ${l.satisfaction?'ok':'neutral'}">${l.satisfaction?'Complétée':'À faire'}</span></td></tr>`).join('')}</tbody></table></div><p class="table-legend">Statuts fictifs pour comparer les états de l’interface. Les signatures et réponses ne peuvent pas être modifiées ici.</p>`,footer:'<button class="btn btn-s" data-close>Revenir aux tâches</button>'});d.addEventListener('click',e=>{const b=e.target.closest('[data-progress-learner]');if(b)openProfile(b.dataset.progressLearner);});}
function openQuestion(){const d=modal({title:'Noter une question ou un besoin',sub:'Session des 13 & 14 octobre · Attribuée à Formateur Démo',narrow:true,kind:'question',body:`<form id="question-form"><label class="field"><span>Qui exprime ce besoin ?</span><select id="question-who"><option value="formateur">Moi, formateur · Formateur Démo</option>${learners.map(l=>`<option value="${l.id}">${l.name}</option>`).join('')}</select></label><label class="field"><span>Question ou besoin</span><textarea id="question-text" maxlength="4000" required placeholder="La question, le besoin ou le cas métier à retenir…"></textarea></label><div class="note-preview">Apparaîtra dans le feedback de session et dans FAQ & Feedback → Demandes.<p id="question-preview"></p></div></form>`,footer:'<button class="btn btn-s" data-close>Annuler</button><button class="btn btn-p" id="save-question" form="question-form" type="submit" disabled>Ajouter la demande</button>'});const input=$('#question-text',d),select=$('#question-who',d),save=$('#save-question',d);const who=()=>select.value==='formateur'?'Formateur Démo':learners.find(l=>l.id===select.value).name;const refresh=()=>{save.disabled=!input.value.trim();$('#question-preview',d).textContent=input.value.trim()?`${who()} : ${input.value.trim()}`:'';};input.addEventListener('input',refresh);select.addEventListener('change',refresh);$('#question-form',d).addEventListener('submit',e=>{e.preventDefault();if(!input.value.trim())return;questions.push({id:'demo-'+(questions.length+1),text:`${who()} : ${input.value.trim()}`,trainer:'Formateur Démo',session:'13 & 14 octobre 2026'});$$('.request-count').forEach(n=>n.textContent=questions.length);d.close();openRequests('session');});input.focus();}
function openRequests(view){const title=view==='faq'?'FAQ & Feedback · Demandes':'Feedback de session';const d=modal({title,sub:'Démonstration · Une même demande est visible dans les deux vues',kind:'requests',body:`<div class="request-top"><span class="pill neutral">${questions.length} demande${questions.length>1?'s':''}</span><button class="btn btn-s" data-other-view>${view==='faq'?'Voir le feedback de session':'Voir dans FAQ & Feedback'} ↗</button></div><div class="request-list">${questions.length?questions.map(q=>`<article class="request-item" data-request-id="${q.id}"><p>${escapeHtml(q.text)}</p><small>Attribuée à ${q.trainer} · Session ${q.session} · ${q.id}</small></article>`).join(''):'<div class="request-empty">Aucune demande dans cette maquette.<br>Utilise « Noter une question ou un besoin » pour en ajouter une.</div>'}</div>`,footer:'<span class="muted">Les demandes de démonstration disparaissent au rechargement.</span><button class="btn btn-s" data-close>Fermer</button>'});$('[data-other-view]',d).addEventListener('click',()=>{d.close();openRequests(view==='faq'?'session':'faq');});}
const prompts={documents:'À partir de ces notes fictives, aide-moi à préparer un compte rendu destiné à mon client.\n\nCommence par identifier les informations manquantes. Distingue les décisions, les actions, les responsables et les échéances. Ne complète pas un fait absent. Propose ensuite un message de relance à relire avant tout envoi.',contenu:'Aide-moi à décliner cette idée de communication pour mon organisation.\n\nDemande-moi le public visé, le ton et les éléments à respecter. Propose trois angles distincts, puis une publication courte et un email. Signale les informations à vérifier et laisse-moi choisir la version à retravailler.'};
function openPrompt(key){const d=modal({title:'Piste de prompt à adapter',sub:'Exemple fictif · À ajuster avec l’apprenant',kind:'prompt',body:`<div class="sample-prompt">${escapeHtml(prompts[key])}</div>`,footer:'<button class="btn btn-s" data-close>Fermer</button><button class="btn btn-p" data-copy>Copier le prompt</button>'});$('[data-copy]',d).addEventListener('click',async e=>{const button=e.currentTarget;try{await navigator.clipboard.writeText(prompts[key]);button.textContent='Copié';}catch{const range=document.createRange();range.selectNodeContents($('.sample-prompt',d));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);button.textContent='Texte sélectionné';}});}
function openCanva(){const d=modal({title:'Diapositives de la session',sub:'Action de la tâche Canva · Démonstration locale',narrow:true,kind:'canva',body:`<p class="muted" style="margin-bottom:20px">Dupliquer et adapter le Canva, puis renseigner le lien de cette session.</p><form id="canva-form"><label class="field"><span>Lien des diapositives</span><input id="canva-link" type="url" required placeholder="https://www.canva.com/…" value="${escapeHtml(slidesLink)}"></label></form>`,footer:'<button class="btn btn-s" data-close>Annuler</button><button class="btn btn-p" type="submit" form="canva-form">Enregistrer dans la maquette</button>'});$('#canva-form',d).addEventListener('submit',e=>{e.preventDefault();slidesLink=$('#canva-link',d).value;d.close();if(activePage!=='dashboard')renderPage();toast('Lien conservé dans cette maquette. Aucun partage effectué.');});}
function runAction(action){if(action==='progress')return openProgress();if(action==='canva')return openCanva();if(action==='feedback')return openRequests('session');if(action==='profiles'){setPage('dashboard');$('#learners-heading').scrollIntoView({block:'nearest',behavior:'smooth'});return;}if(action==='wow'){setPage('dashboard');$('#workshop-ideas').open=true;$('#workshop-ideas').scrollIntoView({block:'nearest',behavior:'smooth'});return;}if(copiedPages.some(p=>p.id===action)){setPage(action);return;}modal({title:action==='qualification'?'Qualification des participants':'Action de la tâche',sub:'Parcours existant DELIV’IA',narrow:true,kind:'existing-action',body:`<div class="status-line">${action==='qualification'?'Le bouton de qualification reste à cet endroit, dans la tâche. La maquette n’ajoute pas de qualification au dashboard.':'Cette action conserve son fonctionnement dans DELIV’IA. La maquette montre son point d’accès, sans envoyer de message ni modifier de donnée.'}</div>`,footer:'<button class="btn btn-s" data-close>Revenir aux tâches</button>'});}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500);}
function reduce(){if($$('dialog[open]').length)return;$('#workspace').hidden=true;$('#compact-stage').hidden=false;openCompact();}
function openCompact(){const d=modal({title:'Session · 13 & 14 octobre 2026',sub:'Paris · Salle Démo · Formateur Démo',kind:'compact-card',narrow:true,body:`<div class="compact-summary"><span class="pill">À préparer</span><p>Niveau 1 · Intermédiaire · 4 apprenants fictifs</p></div><div class="compact-phase"><strong>Préparer & démarrer</strong><p>À partir de J−14 · Étapes et tâches de la session</p><button class="btn btn-p" data-expand>${icon('maximize')}Ouvrir l’espace formateur</button></div><div class="compact-phase"><strong>En formation</strong><p>Jour 1 et jour 2 · Animation et suivi du groupe</p></div>`,footer:'<button class="btn btn-s" data-close>Fermer la carte</button>'});$('[data-expand]',d).addEventListener('click',()=>{d.close();$('#compact-stage').hidden=true;$('#workspace').hidden=false;$('#reduce-button').focus();});}
$('#reduce-button').addEventListener('click',reduce);$('#back-to-card').addEventListener('click',reduce);$('#reopen-card').addEventListener('click',openCompact);$('#new-question').addEventListener('click',openQuestion);$('#faq-button').addEventListener('click',()=>openRequests('faq'));$('#feedback-button').addEventListener('click',()=>openRequests('session'));$('#task-toggle').addEventListener('click',()=>{const open=$('#task-rail').classList.toggle('mobile-open');$('#task-toggle').setAttribute('aria-expanded',String(open));});
renderPage();
